const GOT_POST = "GOT_POST"
const GOT_TITLES = "GOT_TITLES";
const ADD_POST = "ADD"
const EDIT_POST = "EDIT"
const ADD_COMMENT = "COMMENT"
const DELETE_COMMENT = "DELETE_COMMENT"
const DELETE_POST = "DELETE_POST"
const UPDATE_VOTES = "UPDATE_VOTES"

export {
  GOT_POST,
  GOT_TITLES,
  ADD_POST,
  EDIT_POST,
  ADD_COMMENT,
  DELETE_COMMENT,
  DELETE_POST,
  UPDATE_VOTES
}